# Generated by Django 2.2.7 on 2020-01-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getchapp.Channel')),
                ('fullname_en', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname_kr', models.CharField(blank=True, max_length=120, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('getchapp.channel',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getchapp.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=('getchapp.channel',),
        ),
    ]
