# Generated by Django 2.2.7 on 2019-12-28 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL),
        ),
    ]
