# Generated by Django 2.2.7 on 2019-12-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
