# Generated by Django 2.2.7 on 2019-11-28 02:03

from django.db import migrations, models
import django.db.models.deletion
import getchapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'getchapp'), ('model', 'brand')), models.Q(('app_label', 'getchapp'), ('model', 'profile')), models.Q(('app_label', 'getchapp'), ('model', 'item')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=getchapp.models.post_image_path),
        ),
    ]
