# Generated by Django 2.2.7 on 2020-01-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getchapp.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=('getchapp.channel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='getchapp.Channel')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchapp.Pix')),
                ('with_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchapp.Brand')),
                ('with_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchapp.Item')),
            ],
            options={
                'abstract': False,
            },
            bases=('getchapp.channel',),
        ),
    ]
