# Generated by Django 2.2.7 on 2019-12-06 15:05

from django.db import migrations, models
import getchapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0002_auto_20191206_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to=getchapp.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, upload_to=getchapp.models.post_image_path),
        ),
    ]
