# Generated by Django 2.2.7 on 2019-11-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fullname_kr', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname_en', models.CharField(blank=True, max_length=120, null=True)),
                ('keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(default='', upload_to='brand_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
