# Generated by Django 2.2.7 on 2019-12-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0003_auto_20191207_0005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('fullname_en', 'category')},
        ),
    ]
