# Generated by Django 2.2.7 on 2020-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0004_remove_tag_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
