# Generated by Django 2.2.7 on 2019-12-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0005_auto_20191217_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('category', 'image')},
        ),
    ]
