# Generated by Django 2.2.7 on 2020-01-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0006_auto_20200120_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='nbookmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='nreports',
            field=models.IntegerField(default=0),
        ),
    ]
