# Generated by Django 2.2.7 on 2019-12-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0006_auto_20191217_1815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('category', 'fullname_en')},
        ),
    ]
