# Generated by Django 2.2.7 on 2019-12-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getchapp', '0007_auto_20191217_1821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
    ]
